### ISSUE TITLE
Rextester api calls require api key.

### ISSUE THREAD

**Issue by vgoehler** [SebastianZug/WillkommenAufLiaScript#4]
On page executable code (under Markdown Extensions) I get an error while executing the structExample.cpp

`Rextester` api calls require api key. To get one please visit https://www.patreon.com/rextester

Apparently the API Key is not set. :smile: 

Cheers, Keep on the good work!

**Comment by SebastianZug** [comment]
Dear vgoehler,

sorry, I missed replacing the old rextester solution (requiering an api key now)  by our new code runner concept for interactive code snippets. Take a view to [https://github.com/LiaScript/CodeRunner](https://github.com/LiaScript/CodeRunner) to receive more information about supported languages (around 30) and configuration parameters.

Best wishes

Sebastian

https://github.com/SebastianZug/WillkommenAufLiaScript/commit/0f3612c9bfac2eeec81478303ec28d7964c70756

**Comment by vgoehler** [comment]
Thanks for the quick response!
